const fixedPath ='../asstes/PNG/'
const Images = {
    Arrow_down: require(fixedPath+ 'Arrow_down.png'),
    back_arrow: require(fixedPath+ 'back_arrow.png'),
    burger_and_coke: require(fixedPath+ 'burger_and_coke.png'),
    call: require(fixedPath+ 'call.png'),
    Messege: require(fixedPath+ 'Messege.png'),
    cooking_instruction: require(fixedPath+ 'cooking_instruction.png'),
    delete_Icon: require(fixedPath+ 'delete_Icon.png'),
    discount: require(fixedPath+ 'discount.png'),
    facebook: require(fixedPath+ 'facebook.png'),
    food_menu: require(fixedPath+ 'food_menu.png'),
    gestures: require(fixedPath+ 'gestures.png'),
    google: require(fixedPath+ 'google.png'),
    KFC_logo_image: require(fixedPath+ 'KFC_logo_image.png'),
    menu: require(fixedPath+ 'menu.png'),
    package: require(fixedPath+ 'package.png'),
    setting: require(fixedPath+ 'setting.png'),
    MODE: require(fixedPath+ 'MODE.png'),

    UAE_FLAG: require(fixedPath+ 'UAE_FLAG.png'),
    Indian_Flag: require(fixedPath+ 'Indian_Flag.png'),
    Kuwait_Flag: require(fixedPath+ 'Kuwait_Flag.png'),
    Tick_Mark: require(fixedPath+ 'Tick_Mark.png'),
    Easy_Order: require(fixedPath+ 'Easy_Order.png'),

    FoodImage1: require(fixedPath+ 'FoodImage1.png'),
    FoodImage2: require(fixedPath+ 'FoodImage2.png'),
    FoodImage3: require(fixedPath+ 'FoodImage3.png'),
    FoodImage4: require(fixedPath+ 'FoodImage4.png'),
    FoodImage5: require(fixedPath+ 'FoodImage5.png'),
    FoodImage6: require(fixedPath+ 'FoodImage6.png'),
    FoodImage7: require(fixedPath+ 'FoodImage7.png'),
    FoodImage8: require(fixedPath+ 'FoodImage8.png'),
    FoodImage9: require(fixedPath+ 'FoodImage9.png'), 


    KFC_Combo_Pack: require(fixedPath+ 'KFC_Combo_Pack.png'), 
    Green_Tick: require(fixedPath+ 'Green_Tick.png'), 
    Orange_Warning: require(fixedPath+ 'Orange_Warning.png'), 

    Home_Page_Main_Image: require(fixedPath+ 'HomeScreen/Home_Page_Main_Image.png'), 
    Menu: require(fixedPath+ 'HomeScreen/Menu.png'), 
    Location: require(fixedPath+ 'HomeScreen/Location.png'), 
    Chicken_Nugedts: require(fixedPath+ 'HomeScreen/Chicken_Nugedts.png'), 
    Pepsi_Double_Can: require(fixedPath+ 'HomeScreen/Pepsi_Double_Can.png'), 
    French_Fries_Coke: require(fixedPath+ 'HomeScreen/French_Fries_Coke.png'), 
    Chicken_Bucket: require(fixedPath+ 'HomeScreen/Chicken_Bucket.png'), 
    Chicken_Roll: require(fixedPath+ 'HomeScreen/Chicken_Roll.png'), 
    BurgerPNG: require(fixedPath+ 'HomeScreen/BurgerPNG.png'), 
    ChickenNuget: require(fixedPath+ 'HomeScreen/ChickenNuget.png'), 
    ChickenBox: require(fixedPath+ 'HomeScreen/ChickenBox.png'), 

    Favourite_Combo_Pack: require(fixedPath+ 'HomeScreen/Favourite_Combo_Pack.png'), 
    Burger: require(fixedPath+ 'HomeScreen/Burger.png'), 
    Mao_Location: require(fixedPath+ 'HomeScreen/Mao_Location.png'), 
    Cloud: require(fixedPath+ 'HomeScreen/Cloud.png'), 
    Cloud2: require(fixedPath+ 'HomeScreen/Cloud2.png'), 
    laurel_leaves_Left: require(fixedPath+ 'HomeScreen/laurel_leaves_Left.png'), 
    
    Track_Order: require(fixedPath+ 'Sidebar/Track_Order.png'), 
    Great_Menu: require(fixedPath+ 'Sidebar/Great_Menu.png'), 
    Combo_Menu: require(fixedPath+ 'Sidebar/Combo_Menu.png'), 
    Fill_Call: require(fixedPath+ 'Sidebar/Fill_Call.png'), 
    Down_Arrow_Thick: require(fixedPath+ 'Sidebar/Down_Arrow_Thick.png'), 
    Theme_Icon: require(fixedPath+ 'Sidebar/Theme_Icon.png'), 
    Logout_Icon: require(fixedPath+ 'Sidebar/Logout_Icon.png'),

    Search_Icon: require(fixedPath+ 'MenuScreen/Search_Icon.png'), 
    Thin_Back_Icon: require(fixedPath+ 'MenuScreen/Thin_Back_Icon.png'), 
    Foood_Menu_Icon: require(fixedPath+ 'MenuScreen/Foood_Menu_Icon.png'), 
    Favourite_Icon_Empty: require(fixedPath+ 'MenuScreen/Favourite_Icon_Empty.png'), 
    Favourite_Icon: require(fixedPath+ 'MenuScreen/Favourite_Icon.png'), 
    Cross_Icon: require(fixedPath+ 'MenuScreen/Cross_Icon.png'), 
    Delete_Icon: require(fixedPath+ 'MenuScreen/Delete_Icon.png'), 
    AddButton: require(fixedPath+ 'MenuScreen/AddButton.png'), 
    Minus: require(fixedPath+ 'MenuScreen/Minus.png'), 
    CoffeeCup: require(fixedPath+ 'MenuScreen/CoffeeCup.png'), 
    SpilledWater: require(fixedPath+ 'MenuScreen/SpilledWater.png'), 
    Bow_Tie: require(fixedPath+ 'MenuScreen/Bow_Tie.png'), 

    DeliveryBike: require(fixedPath+ 'CheckOutScreen/DeliveryBike.png'), 
    COD_Cash: require(fixedPath+ 'CheckOutScreen/COD_Cash.png'), 
    CreditCard: require(fixedPath+ 'CheckOutScreen/CreditCard.png'), 
    Visa_Text: require(fixedPath+ 'CheckOutScreen/Visa_Text.png'), 
    HomeIcon: require(fixedPath+ 'CheckOutScreen/HomeIcon.png'), 
    GreenPhoneCall: require(fixedPath+ 'CheckOutScreen/GreenPhoneCall.png'), 
    RoundLoader: require(fixedPath+ 'CheckOutScreen/RoundLoader.png'), 
    CredtiCardStack: require(fixedPath+ 'CheckOutScreen/CredtiCardStack.png'), 
    ApplePay: require(fixedPath+ 'CheckOutScreen/ApplePay.png'), 
    ClickToPay: require(fixedPath+ 'CheckOutScreen/ClickToPay.png'), 
    CashIcon: require(fixedPath+ 'CheckOutScreen/CashIcon.png'), 

    EmptyBox: require(fixedPath+ 'CartScreens/EmptyBox.png'), 
    Edit_Icon: require(fixedPath+ 'CartScreens/Edit_Icon.png'), 
    Info_Button: require(fixedPath+ 'CartScreens/Info_Button.png'), 

    DownloadIcon: require(fixedPath+ 'OrderScreen/DownloadIcon.png'), 
    OvenIcon: require(fixedPath+ 'OrderScreen/OvenIcon.png'), 
    PopCornCup: require(fixedPath+ 'OrderScreen/PopCornCup.png'), 
}
export default Images   