import { useLanguage } from '../context/LanguageContex'

const en = {
  // screens
  HomeScreen: 'HomeScreen',
  ChangeLocationBottomSheetScreen: 'ChangeLocationBottomSheetScreen',
  MapsScreen: 'MapsScreen',
  PopUpScreens: 'PopUpScreens',
  LoginScreen: 'LoginScreen',
  LoginScreen2: 'LoginScreen2',
  LoginPageCountryBottomSheetScreen: 'LoginPageCountryBottomSheetScreen',
  OTPScreen: 'OTPScreen',
  FAQPageScreen: 'FAQPageScreen',
  DealsAndOfferScreen: 'DealsAndOfferScreen',
  CreateProfileScreen: 'CreateProfileScreen',
  FontsScreen: 'FontsScreen',
  SplashScreen: 'SplashScreen',
  ExploreMenuScreen: 'ExploreMenuScreen',
  MenuCategorizeScreen: 'MenuCategorizeScreen',
  FoodCustomizationScreen: 'FoodCustomizationScreen',
  CartScreen: 'CartScreen',
  RemoveCartItemBottomSheetScreen: 'RemoveCartItemBottomSheetScreen',
  SearchScreen: 'SearchScreen',
  CheckOutScreen: 'CheckOutScreen',
  PaymentModalScreen: "PaymentModalScreen",
  OrderStatusScreen: 'OrderStatusScreen',
  TrackOrderScreen: 'TrackOrderScreen',
  OrderHistoryScreens: 'OrderHistoryScreens',
  OrderDetailsScreen: 'OrderDetailsScreen',
  OfferAppliedScreen: "OfferAppliedScreen",
  HelpScreen: 'HelpScreen',
  Main: 'Main',
  Help: 'Help',

  fonOneString: 'For One',
  dealsString: 'Deals',
  slideDesertString: 'Slides & Deserts',
  forSharingString: 'For Sharing',
  sandwichString: 'SandWich',
  cashOnDeliveryString: 'Cash On Delivery',
  onlineString : 'Online',
  creditCardString: 'Credit Card',
  visaString: 'Visa Checkout',
  beingPreparedString: 'Being Prepared',
  deliveredString : 'Delivered',
  cancelledString : "Cancelled",
  // landing
  lickingGood: "It's finger lickin' good",

  // login
  KFC: 'KFC',
  loginToUlock: 'Login to Unlock',
  awesomeNewFeature: 'awesome new features',
  fingerLicking: 'Finger\nLickin Good',
  dealAndOfferTxt: 'Great\nDeals & Offers',
  easyOrdering: 'Easy \nOrdering',
  chooseLanguage: 'Choose Language',
  english: 'English',
  arabic: 'عربي',
  uae: 'UAE',
  kuwait: 'Kuwait',
  india: 'India',
  login: 'LOGIN',
  logout: 'Log Out',
  termsCondition: 'Terms & Conditons',
  skipLogin: 'SKIP LOGIN',
  change: 'Change',

  // country bottomsheet 
  welcome: 'Welcome to KFC',
  countryDescription: 'Now  you can order in the following countries using this App. Please select the country where you want to place order 😎',
  needToHaveLocalNumber: 'You need to have a local number',
  done: 'Done',

  // loginPage 2 
  welcome2: 'Welcome to all new',
  app: 'app',
  loginWIthNumberText: 'Login with valid',
  mobileNumber: 'Mobile number',
  shouldBeXDigit: 'Mobile number should be 10 digit ',
  EgMobile: 'eg 987 654 123',
  enterNumberPlaceHoler: 'Mobile Number ',
  loginWithSocialHeader: 'Login with Social Accounts',
  facebook: 'Facebook',
  google: 'google',
  tc: 't&c',
  skipLoginAndContinue: 'skip login & continue',
  submit: 'submit',


  // otp auth
  otpText: 'One Time Password',
  enterOtpHeader: 'Please enter the 4 digit OTP sent to ',
  resendOtp: 'Resend OTP',
  callMe: 'Call Me',
  verifyText: 'VERIFY',

  // create profile 
  createProfileHeader: 'Create Profile',
  enterYourDetails: 'Please enter your details',
  name: 'Name',
  email: 'Email',
  save: 'Save',
  fieldIsMandatory: 'This field is mandatory.',

  // home screen 
  deliveryTo: 'Deliver to',
  exploreMore: 'Explore more',
  viewAll: 'view all',
  deals: 'Deals',
  forOne: 'for\none',
  sideDeserts: 'side\ndeserts',
  forSharing: 'for\nsharing',
  beverages: 'beverages',
  CurrentOrder: 'Current Order',
  trackOrder: 'Track Order',
  refresh: 'Refresh',
  orderIdText: 'Order ID',
  bestSeller: 'best sellers',
  favourites: 'favourites',
  orderFromList: 'Order from your favourite list of items',
  orderNow: 'order now',
  order: 'order',
  onTheAbove: 'On The Above',
  cashback: 'cashback',

  // location botom sheet 
  consfirmLocation: 'Confirm Location',
  consfirmLocationDescription: 'Your delivery location has been identified\nPlease confirm to proceed ⛳',
  confirm: 'confirm',
  // sidebar 
  orderHistory: 'Order History',
  dealsAndOffer: 'Deals & Offers',
  greatMenu: 'Great Menu',
  combo: 'Combo',
  language: 'Language',
  languageToggle: 'اللغة',
  country: 'Country',
  callSupport: 'call support',
  faq: 'faq',
  nutritionInfo: 'Nutrition Information',
  pleaseSelectlanguage: 'Please Select language',
  ChangeTheme: 'Change Theme',

  // explore screen 
  exploreMenu: 'Explore Menu',
  AddToCart: 'Add To Cart',
  customize: 'customize',
  menuCategorizationHeader: 'Menu Categories',
  bestSeller2: 'BestSellers',
  viewCart: 'View Cart',
  youSaved: 'you Saved',
  cart: 'Cart',
  placeOrder: 'Place Order',
  addMoreItemsToCart: 'Add more items in your cart',
  applyCoupon: 'Apply Coupon',
  couponApplied: 'Coupon Applied',
  WhatsNew: "What's New",
  bottomKFCDescription: "kfc | kentucky fried wings | lost in the sauce",
  opps: 'opps!',
  search: 'Search',
  noResFound: "No result found for your search! ",
  exploreKFCMenu: 'explore KFC Menu',
  cancel: 'Cancel',
  yesConfirm: 'yes,Confirm',
  confirmAskingText: 'Are you sure you want to remove this product from your cart 🧐',
  edit: 'edit',
  items: 'Items',
  SubTotal: 'Sub Total',
  discount: 'Discount',
  vat: 'vat',
  deliveriCharge: 'Delivery Charge',
  grandTotal: 'Grand Total',
  offerApplied: 'Offer Applied 🤟🤟',
  offer: 'Offer',
  applied: 'Applied',
  gotIt: 'Got It',
  offerAvailText: 'Congratulations, complete your order to avail this offer',
  delete: 'Delete',

  completeYourAddress: 'Complete your address',
  iWant: 'I Want',
  pickup: 'pickup',
  delivery: 'delivery',
  sorryNotDeliver: 'Soorry we do not deliver here',
  tagLocation: 'Tag location',
  address: 'Address',
  buildingName: 'Building Name',
  flatNo: 'Flat No',
  home: 'home',
  office: 'Office',
  hotel: 'Hotel',
  other: 'Other',
  confirmLocation: 'Confirm Location',
  saveLocationConfirmation: 'Are you sure you want to save this location?',

  checkOut: 'Checkout',
  wantOrder: 'I want my order:',
  deliverNow: 'Deliver Now',
  deliveryLater: 'Deliver Later',
  deliveryAddress: 'Delivery Address',
  contactLessDelivery: '100% contactless delivery',
  amountToBepaid: 'Amount to be paid',
  paymentMode: 'SELECT PAYMENT MODE',
  paymentMethods: 'Payment Method',
  makePayment: 'Make Payment',
  cashOnDelivery: 'Cash On Delivery',
  creditDebitcards: 'Credit/Debit Cards',
  visaCheckOut: 'Visa Check Out',
  makePreferredMode: 'Make this as my preferred mode!',
  payByCash: 'Pay By Cash',
  addCreditDebitCard: 'addCreditDebitCard',
  otherPaymentMethod: 'Other Payment Method',
  savedCards: 'Saved Cards',
  otherPaymentOptions: 'Other Payment Options',
  success: 'Success',
  failed: 'Failed',
  currentOrders: 'Current Orders',
  previousOrders: 'Previous Orders',
  orderId: 'Order ID',
  NoOrdersYet: 'No Orders Yet!',
  makeAOrder: 'Make a Order now',
  OrderDetail: 'Order Detail',
  qty: 'Qty',
  orderStatus: 'Order Status',
  KFC_restaurant: 'KFC Restaurant',
  orderConfired: 'Order Confirmed',
  pendingConfirmation: 'Pending Confirmation',
  orderFailed: 'Oops! The Order Failed',
  waitingOrder: 'We are waiting for the restaurant to confirm your order',
  PaymentMode: 'Payment Mode : ',
  OrderNo: 'Order No.',
  orderSummary: 'Order Summanry',
  unableToProcess: 'Unable to process your order',
  tryAgainMsg: 'Please try again after 15 minutes or call us on',
  refundInitiated: 'Refund initiated',
  refundMessage: 'We have initiated a refund of',
  refundMessage2: 'back to your payment instrument. Generally, the refund takes 4-10 business days to reflect in your account.',
  writeToUs: 'Write to us',
  writeMessage: 'For any queries, email us quoting your mobile number',

  // track order 
  details: 'Details',
  cod: 'cod',
  next: 'next',
  onTheWay: 'On The Way',
  beingPrepared: 'Being Prepared',
  foodPrepared: 'The food is being prepared',
  orderNo: 'order No',
  currentStatus: 'Current Status',

  // FAQ 
  faqHeader: 'FAQ',
  generalQuestions: 'General Questions',
  orderingQuestions: 'Ordering & Delivery',
  paymentsQuestions: 'Payments & Refunds',
  accountQuestions: 'Account & Profile',
  faqs: "FAQ's",
  onlineOrdering: 'Online Ordering',
  restaurants: 'Restaurants',
  employment: 'Employment',

  // top 7 items
  resetPassword: 'How do I reset my password?',
  restaurantReceive: 'How do I know if the restaurant received my order?',
  paymentOptions: 'What payment options are available?',
  saveCreditCard: 'Is it safe to save my credit card?',
  changeAccountInfo: 'How can I change my account information?',
  deliveryChargesHigher: 'Why are delivery charges higher sometimes?',
  deliveryServiceCharge: 'What is the delivery service charge?',
  resetPasswordA: 'You can reset your password from the login screen by selecting “Forgot Password” and following the instructions.',
  restaurantReceiveA: 'Once your order is placed, the restaurant receives it instantly. You will also see real-time updates in your order status.',
  paymentOptionsA: 'We accept multiple payment options including credit/debit cards, wallet payments, and cash on delivery depending on availability.',
  saveCreditCardA: 'Yes, saving your card is secure. Your payment details are encrypted and never shared with third parties.',
  changeAccountInfoA: 'You can change your personal details from the Profile or Account Settings section in the app.',
  deliveryChargesHigherA: 'Delivery charges may vary based on distance, peak hours, or high-demand situations.',
  deliveryServiceChargeA: 'This charge helps cover operational costs such as delivery support, app maintenance, and service improvements.',


  // FAQ – Full Q&A List
  faqQ1: 'What is KFC Rewards?',
  faqA1: 'KFC Rewards is a loyalty program where you earn points every time you order.',

  faqQ2: 'How can I track my order?',
  faqA2: 'You can track your order in real-time from the "Current Order" section.',

  faqQ3: 'What payment methods do you accept?',
  faqA3: 'We support Cash on Delivery, Credit/Debit Cards and online payments.',

  faqQ4: 'How do I update my profile details?',
  faqA4: 'You can update your profile from the “Account” section in the sidebar.',

  faqQ5: 'Can I change my order after placing it?',
  faqA5: 'Order changes depend on restaurant preparation stage. Contact support quickly.',

  faqQ6: 'What should I do if my order is late?',
  faqA6: 'You can check status in “Current Orders” or contact customer support.',

  faqQ7: 'Will I get a refund for cancelled orders?',
  faqA7: 'Refunds depend on payment method, usually processed within 3–5 days.',

  faqQ8: 'Can I delete my account?',
  faqA8: 'Yes, you can request account deletion from the profile settings.',

  faqQ9: 'How can I apply for a job?',
  faqA9: 'You can apply directly through our careers section or job portal.',

  faqQ10: 'Where can I check my interview status?',
  faqA10: 'You can track your interview status in the application dashboard.',

  faqQ11: 'Do you offer part-time positions?',
  faqA11: 'Yes, part-time positions are available depending on current openings.',

  allOffers: 'All Offers',
  apply: 'Apply'

} as const

const ar = {
  // screens
  HomeScreen: 'HomeScreen',
  ChangeLocationBottomSheetScreen: 'ChangeLocationBottomSheetScreen',
  MapsScreen: 'MapsScreen',
  PopUpScreens: 'PopUpScreens',
  LoginScreen: 'LoginScreen',
  LoginScreen2: 'LoginScreen2',
  LoginPageCountryBottomSheetScreen: 'LoginPageCountryBottomSheetScreen',
  OTPScreen: 'OTPScreen',
  FAQPageScreen: 'FAQPageScreen',
  DealsAndOfferScreen: 'DealsAndOfferScreen',
  CreateProfileScreen: 'CreateProfileScreen',
  FontsScreen: 'FontsScreen',
  SplashScreen: 'SplashScreen',
  ExploreMenuScreen: 'ExploreMenuScreen',
  MenuCategorizeScreen: 'MenuCategorizeScreen',
  FoodCustomizationScreen: 'FoodCustomizationScreen',
  CartScreen: 'CartScreen',
  RemoveCartItemBottomSheetScreen: 'RemoveCartItemBottomSheetScreen',
  SearchScreen: 'SearchScreen',
  CheckOutScreen: 'CheckOutScreen',
  PaymentModalScreen: 'PaymentModalScreen',
  OrderStatusScreen: 'OrderStatusScreen',
  TrackOrderScreen: 'TrackOrderScreen',
  OrderHistoryScreens: 'OrderHistoryScreens',
  OrderDetailsScreen: 'OrderDetailsScreen',
  OfferAppliedScreen: "OfferAppliedScreen",
  HelpScreen: 'HelpScreen',
  Main: 'Main',
  Help: 'Help',

  fonOneString: 'For One',
  dealsString: 'Deals',
  slideDesertString: 'Slides & Deserts',
  forSharingString: 'For Sharing',
  sandwichString: 'SandWich',
  cashOnDeliveryString: 'Cash On Delivery',
   onlineString : 'Online',
  creditCardString: 'Credit Card',
  visaString: 'Visa Checkout',
  beingPreparedString: 'Being Prepared',
  deliveredString : 'Delivered',
  cancelledString : "Cancelled",
  // landing
  lickingGood: 'إنه لذيذ للغاية',

  // country bottomsheet
  welcome: 'مرحبًا بكم في كنتاكي',
  countryDescription: 'يمكنك الآن الطلب في البلدان التالية باستخدام هذا التطبيق. يرجى اختيار البلد الذي ترغب في تقديم الطلب فيه 😎',
  needToHaveLocalNumber: 'يجب أن يكون لديك رقم محلي',
  done: 'تم',

  // login
  KFC: 'كنتاكي',
  loginToUlock: 'سجّل الدخول لفتح',
  awesomeNewFeature: 'مميزات جديدة مذهلة',
  fingerLicking: 'طعم\nلا يُقاوم',
  dealAndOfferTxt: 'عروض\nوصفقات رائعة',
  easyOrdering: 'طلب\nسهل وسريع',
  chooseLanguage: 'اختر اللغة',
  english: 'English',
  arabic: 'العربية',
  uae: 'الإمارات',
  login: 'تسجيل الدخول',
  logout: 'Log Out',
  termsCondition: 'الشروط والأحكام',
  skipLogin: 'تخطي تسجيل الدخول',
  change: 'تغيير',

  // loginPage 2 
  welcome2: 'مرحبًا بكم في التطبيق الجديد',
  app: 'التطبيق',
  loginWIthNumberText: 'سجّل الدخول برقم صالح',
  mobileNumber: 'رقم الجوال',
  shouldBeXDigit: 'يجب أن يكون رقم الجوال مكونًا من 10 أرقام',
  EgMobile: 'eg 987 654 123',
  enterNumberPlaceHoler: 'أدخل رقم الجوال',
  loginWithSocialHeader: 'سجّل الدخول عبر الحسابات الاجتماعية',
  facebook: 'فيسبوك',
  google: 'جوجل',
  tc: 'الشروط والأحكام',
  skipLoginAndContinue: 'تخطّ تسجيل الدخول واستمر',
  submit: 'إرسال',


  // otp auth
  otpText: 'رمز التحقق لمرة واحدة',
  enterOtpHeader: 'يرجى إدخال رمز التحقق المكون من 4 أرقام المرسل إلى',
  resendOtp: 'إعادة إرسال الرمز',
  callMe: 'اتصل بي',
  verifyText: 'تحقق',

  // create profile 
  createProfileHeader: 'إنشاء الملف الشخصي',
  enterYourDetails: 'يرجى إدخال بياناتك',
  name: 'الاسم',
  email: 'البريد الإلكتروني',
  save: 'حفظ',
  fieldIsMandatory: 'هذا الحقل إلزامي.',

  // home screen 
  deliveryTo: 'التوصيل إلى',
  exploreMore: 'استكشاف المزيد',
  viewAll: 'عرض الكل',
  deals: 'عروض',
  forOne: 'لشخص واحد',
  sideDeserts: 'حلويات جانبية',
  forSharing: 'للمشاركة',
  beverages: 'مشروبات',
  CurrentOrder: 'الطلب الحالي',
  trackOrder: 'تتبع الطلب',
  refresh: 'تحديث',
  orderIdText: 'رقم الطلب',
  bestSeller: 'الأكثر مبيعًا',
  favourites: 'المفضلة',
  orderFromList: 'اطلب من قائمتك المفضلة من العناصر',
  orderNow: 'اطلب الآن',
  order: 'طلب',
  cashback: 'استرداد نقدي',
  onTheAbove: 'على ما سبق',

  // location bottom sheet 
  consfirmLocation: 'تأكيد الموقع',
  consfirmLocationDescription: 'تم تحديد موقع التوصيل الخاص بك\nيرجى التأكيد للمتابعة ⛳',
  confirm: 'تأكيد',

  // sidebar 
  orderHistory: 'سجل الطلبات',
  dealsAndOffer: 'العروض والخصومات',
  greatMenu: 'قائمة رائعة',
  combo: 'وجبات كومبو',
  language: 'اللغة',
  languageToggle: 'language',
  country: 'البلد',
  callSupport: 'الاتصال بالدعم',
  faq: 'الأسئلة الشائعة',
  nutritionInfo: 'المعلومات الغذائية',
  pleaseSelectlanguage: 'يرجى اختيار اللغة',
  ChangeTheme: 'تغيير المظهر',

  // explore screen 
  exploreMenu: 'استكشف القائمة',
  AddToCart: 'أضف إلى السلة',
  customize: 'تخصيص',
  menuCategorizationHeader: 'تصنيفات القائمة',
  bestSeller2: 'الأكثر مبيعًا',
  viewCart: 'عرض السلة',
  youSaved: 'لقد وفّرت',
  cart: 'السلة',
  placeOrder: 'إتمام الطلب',
  addMoreItemsToCart: 'أضف المزيد من الأصناف إلى سلتك',
  applyCoupon: 'تطبيق الكوبون',
  couponApplied: 'تم تطبيق القسيمة',
  WhatsNew: 'ما الجديد',
  bottomKFCDescription: "كنتاكي | أجنحة كنتاكي المقلية | غارق في الصوص",
  opps: 'عذرًا!',
  search: 'بحث',
  noResFound: 'لا توجد نتائج لبحثك!',
  exploreKFCMenu: 'استكشف قائمة KFC',
  cancel: 'إلغاء',
  yesConfirm: 'نعم، تأكيد',
  confirmAskingText: 'هل أنت متأكد أنك تريد إزالة هذا المنتج من سلتك؟ 🧐',
  edit: 'تعديل',
  items: 'عناصر',
  SubTotal: 'المجموع الفرعي',
  discount: 'الخصم',
  vat: 'ضريبة القيمة المضافة',
  deliveriCharge: 'رسوم التوصيل',
  grandTotal: 'الإجمالي الكلي',
  offerApplied: 'تم تطبيق العرض 🤟🤟',
  offer: 'عرض',
  applied: 'تم التطبيق',
  gotIt: 'حسنًا',
  offerAvailText: 'تهانينا، أكمل طلبك للحصول على هذا العرض',
  delete: 'حذف',

  completeYourAddress: 'أكمل عنوانك',
  iWant: 'أريد',
  pickup: 'استلام',
  delivery: 'توصيل',
  sorryNotDeliver: 'عذرًا، لا نوصل إلى هذا الموقع',
  tagLocation: 'تحديد الموقع',
  address: 'العنوان',
  buildingName: 'اسم المبنى',
  flatNo: 'رقم الشقة',
  home: 'منزل',
  office: 'مكتب',
  hotel: 'فندق',
  other: 'أخرى',
  confirmLocation: 'تأكيد الموقع',
  saveLocationConfirmation: 'هل أنت متأكد أنك تريد حفظ هذا الموقع؟',

  checkOut: 'الدفع',
  wantOrder: 'أريد طلبي:',
  deliverNow: 'التوصيل الآن',
  deliveryLater: 'التوصيل لاحقًا',
  deliveryAddress: 'عنوان التوصيل',
  contactLessDelivery: 'توصيل بدون تلامس 100%',
  amountToBepaid: 'المبلغ المستحق',
  paymentMode: 'اختر وسيلة الدفع',
  paymentMethods: 'طرق الدفع',
  makePayment: 'إتمام الدفع',
  cashOnDelivery: 'الدفع عند الاستلام',
  creditDebitcards: 'بطاقات الائتمان/الخصم',
  visaCheckOut: 'الدفع عبر فيزا',
 makePreferredMode: 'Make this as my preferred mode!!',
  payByCash: 'الدفع نقداً',
  addCreditDebitCard: 'إضافة بطاقة ائتمان/خصم',
  otherPaymentMethod: 'طرق دفع أخرى',
  savedCards: 'البطاقات المحفوظة',
  otherPaymentOptions: 'خيارات دفع أخرى',

  success: 'نجاح',
  failed: 'فشل',
  currentOrders: 'الطلبات الحالية',
  previousOrders: 'الطلبات السابقة',

  orderId: 'رقم الطلب',
  NoOrdersYet: 'لا توجد أي طلبات بعد!',
  makeAOrder: 'قم بعمل طلب',
  OrderDetail: 'تفاصيل الطلب',
  qty: 'الكمية',
  orderStatus: 'حالة الطلب',

  KFC_restaurant: 'مطعم KFC',

  orderConfired: 'تم تأكيد الطلب',
  pendingConfirmation: 'بانتظار التأكيد',
  orderFailed: 'عذراً! فشل الطلب',

  waitingOrder: 'نحن ننتظر المطعم لتأكيد طلبك',

  PaymentMode: 'طريقة الدفع',
  OrderNo: 'رقم الطلب',
  orderSummary: 'ملخص الطلب',

  unableToProcess: 'يتعذر معالجة طلبك',
  tryAgainMsg: 'الرجاء المحاولة مرة أخرى بعد 15 دقيقة أو الاتصال بنا على',

  refundInitiated: 'تم بدء عملية الاسترداد',
  refundMessage: 'لقد قمنا ببدء استرداد مبلغ',
  refundMessage2: 'إلى وسيلة الدفع الخاصة بك. عادةً يستغرق ظهور المبلغ 4-10 أيام عمل في حسابك.',

  writeToUs: 'تواصل معنا',
  writeMessage: 'لأي استفسارات، يرجى مراسلتنا مع ذكر رقم هاتفك',

  // track order 
  details: 'التفاصيل',
  cod: 'الدفع عند الاستلام',
  next: 'التالي',
  onTheWay: 'في الطريق',
  beingPrepared: 'قيد التحضير',
  foodPrepared: 'جاري تحضير الطعام',
  orderNo: 'رقم الطلب',
  currentStatus: 'الحالة الحالية',

  // FAQ
  faqHeader: 'الأسئلة الشائعة',
  generalQuestions: 'الأسئلة العامة',
  orderingQuestions: 'الطلبات والتوصيل',
  paymentsQuestions: 'الدفع والاسترداد',
  accountQuestions: 'الحساب والملف الشخصي',
  faqs: "الأسئلة الشائعة",
  onlineOrdering: 'الطلب عبر الإنترنت',
  restaurants: 'المطاعم',
  employment: 'التوظيف',

  resetPassword: 'كيف يمكنني إعادة تعيين كلمة المرور؟',
  restaurantReceive: 'كيف أعرف أن المطعم استلم طلبي؟',
  paymentOptions: 'ما هي خيارات الدفع المتاحة؟',
  saveCreditCard: 'هل من الآمن حفظ بطاقة الائتمان؟',
  changeAccountInfo: 'كيف يمكنني تغيير معلومات حسابي؟',
  deliveryChargesHigher: 'لماذا تكون رسوم التوصيل أعلى أحيانًا؟',
  deliveryServiceCharge: 'ما هي رسوم خدمة التوصيل؟',
  resetPasswordA: 'يمكنك إعادة تعيين كلمة المرور من شاشة تسجيل الدخول عن طريق اختيار "هل نسيت كلمة المرور؟" واتباع التعليمات.',
  restaurantReceiveA: 'بمجرد إتمام طلبك، يستلمه المطعم مباشرة. كما ستتمكن من رؤية التحديثات لحالة طلبك في الوقت الفعلي.',
  paymentOptionsA: 'نقبل عدة طرق دفع، بما في ذلك البطاقات الائتمانية/الخصم، المحافظ الإلكترونية، والدفع عند التسليم حسب التوفر.',
  saveCreditCardA: 'نعم، حفظ بطاقتك آمن. يتم تشفير بيانات الدفع الخاصة بك ولن تتم مشاركتها مع أي طرف آخر.',
  changeAccountInfoA: 'يمكنك تعديل معلوماتك الشخصية من قسم الملف الشخصي أو إعدادات الحساب داخل التطبيق.',
  deliveryChargesHigherA: 'قد تختلف رسوم التوصيل حسب المسافة، أو ساعات الذروة، أو فترات الطلب المرتفع.',
  deliveryServiceChargeA: 'تُستخدم هذه الرسوم لتغطية التكاليف التشغيلية مثل دعم التوصيل، صيانة التطبيق، وتحسين الخدمات.',


  // FAQ – Full Q&A List
  faqQ1: 'ما هو برنامج مكافآت كنتاكي؟',
  faqA1: 'هو برنامج ولاء تحصل فيه على نقاط في كل مرة تطلب فيها.',

  faqQ2: 'كيف يمكنني تتبع طلبي؟',
  faqA2: 'يمكنك تتبع طلبك من قسم "الطلب الحالي".',

  faqQ3: 'ما طرق الدفع المتاحة؟',
  faqA3: 'ندعم الدفع عند الاستلام وبطاقات الائتمان والدفع الإلكتروني.',

  faqQ4: 'كيف أقوم بتحديث بيانات ملفي الشخصي؟',
  faqA4: 'يمكنك تحديث معلوماتك من قسم "الحساب" في القائمة الجانبية.',

  faqQ5: 'هل يمكنني تعديل الطلب بعد إرساله؟',
  faqA5: 'يعتمد ذلك على مرحلة تجهيز الطلب، من الأفضل التواصل مع الدعم.',

  faqQ6: 'ماذا أفعل إذا تأخر طلبي؟',
  faqA6: 'تحقق من قسم "الطلبات الحالية" أو تواصل مع الدعم.',

  faqQ7: 'هل سأحصل على استرداد في حال إلغاء الطلب؟',
  faqA7: 'تعتمد سياسة الاسترداد على طريقة الدفع، وتتم عادة خلال 3–5 أيام.',

  faqQ8: 'هل يمكنني حذف حسابي؟',
  faqA8: 'نعم، يمكنك طلب حذف الحساب من إعدادات الملف الشخصي.',

  faqQ9: 'كيف يمكنني التقديم على وظيفة؟',
  faqA9: 'يمكنك التقديم مباشرة من خلال قسم الوظائف أو بوابة التوظيف لدينا.',

  faqQ10: 'أين يمكنني متابعة حالة مقابلتي؟',
  faqA10: 'يمكنك متابعة حالة المقابلة من خلال لوحة التحكم الخاصة بالطلبات.',

  faqQ11: 'هل توفرون وظائف بدوام جزئي؟',
  faqA11: 'نعم، تتوفر وظائف بدوام جزئي حسب الشواغر الحالية.',

  allOffers: 'جميع العروض',
  apply: 'تطبيق'
} as const

export const useStrings = () => {
  const { language } = useLanguage();
  return language === 'ar' ? ar : en;
};
