import { useLanguage } from '../context/LanguageContex'

const en = {
  // screens
  HomeScreen: 'HomeScreen',
  ChangeLocationBottomSheetScreen: 'ChangeLocationBottomSheetScreen',
  MapsScreen: 'MapsScreen',
  PopUpScreens: 'PopUpScreens',
  LoginScreen: 'LoginScreen',
  LoginScreen2: 'LoginScreen2',
  LoginPageCountryBottomSheetScreen: 'LoginPageCountryBottomSheetScreen',
  OTPScreen: 'OTPScreen',
  CreateProfileScreen: 'CreateProfileScreen',
  FontsScreen: 'FontsScreen',
  SplashScreen: 'SplashScreen',
  ExploreMenuScreen: 'ExploreMenuScreen',
  MenuCategorizeScreen: 'MenuCategorizeScreen',
  CartScreen: 'CartScreen',
  RemoveCartItemBottomSheetScreen: 'RemoveCartItemBottomSheetScreen',
  SearchScreen: 'SearchScreen',
  CheckOutScreen: 'CheckOutScreen',
  OrderHistoryScreens: 'OrderHistoryScreens',
  OfferAppliedScreen: "OfferAppliedScreen",
  HelpScreen: 'HelpScreen',
  Main: 'Main',
  Help: 'Help',

  // landing
  lickingGood: "It's finger lickin' good",

  // login
  KFC: 'KFC',
  loginToUlock: 'Login to Unlock',
  awesomeNewFeature: 'awesome new features',
  fingerLicking: 'Finger\nLickin Good',
  dealAndOfferTxt: 'Great\nDeals & Offers',
  easyOrdering: 'Easy \nOrdering',
  chooseLanguage: 'Choose Language',
  english: 'English',
  arabic: 'عربي',
  uae: 'UAE',
  kuwait: 'Kuwait',
  india: 'India',
  login: 'LOGIN',
  logout: 'Log Out',
  termsCondition: 'Terms & Conditons',
  skipLogin: 'SKIP LOGIN',
  change: 'Change',

  // country bottomsheet 
  welcome: 'Welcome to KFC',
  countryDescription: 'Now  you can order in the following countries using this App. Please select the country where you want to place order 😎',
  needToHaveLocalNumber: 'You need to have a local number',
  done: 'Done',

  // loginPage 2 
  welcome2: 'Welcome to all new',
  app: 'app',
  loginWIthNumberText: 'Login with valid',
  mobileNumber: 'Mobile number',
  shouldBeXDigit: 'Mobile number should be 10 digit ',
  EgMobile: 'eg 987 654 123',
  enterNumberPlaceHoler: 'Mobile Number ',
  loginWithSocialHeader: 'Login with Social Accounts',
  facebook: 'Facebook',
  google: 'google',
  tc: 't&c',
  skipLoginAndContinue: 'skip login & continue',
  submit: 'submit',


  // otp auth
  otpText: 'One Time Password',
  enterOtpHeader: 'Please enter the 4 digit OTP sent to ',
  resendOtp: 'Resend OTP',
  callMe: 'Call Me',
  verifyText: 'VERIFY',

  // create profile 
  createProfileHeader: 'Create Profile',
  enterYourDetails: 'Please enter your details',
  name: 'Name',
  email: 'Email',
  save: 'save',
  fieldIsMandatory: 'This field is mandatory.',

  // home screen 
  deliveryTo: 'Deliver to',
  exploreMore: 'Explore more',
  viewAll: 'view all',
  deals: 'deals',
  forOne: 'for\none',
  sideDeserts: 'side\ndeserts',
  forSharing: 'for\nsharing',
  beverages: 'beverages',
  CurrentOrder: 'Current Order',
  trackOrder: 'Track Order',
  orderIdText: 'Order ID',
  bestSeller: 'best sellers',
  favourites: 'favourites',
  orderFromList: 'Order from your favourite list of items',
  orderNow: 'order now',
  order: 'order',

  // location botom sheet 
  consfirmLocation: 'Confirm Location',
  consfirmLocationDescription: 'Your delivery location has been identified\nPlease confirm to proceed ⛳',
  confirm: 'confirm',
  // sidebar 
  orderHistory: 'Order History',
  dealsAndOffer: 'Deals & Offers',
  greatMenu: 'Great Menu',
  combo: 'Combo',
  language: 'Language',
  languageToggle: 'اللغة',
  country: 'Country',
  callSupport: 'call support',
  faq: 'faq',
  nutritionInfo: 'Nutrition Information',
  pleaseSelectlanguage: 'Please Select language',
  ChangeTheme: 'Change Theme',

  // explore screen 
  exploreMenu: 'Explore Menu',
  AddToCart: 'Add To Cart',
  customize: 'customize',
  menuCategorizationHeader: 'Menu Categories',
  bestSeller2: 'BestSellers',
  viewCart: 'View Cart',
  youSaved: 'you Saved',
  cart: 'Cart',
  placeOrder: 'Place Order',
  addMoreItemsToCart: 'Add more items in your cart',
  applyCoupon: 'Apply Coupon',
  WhatsNew: "What's New",
  bottomKFCDescription: "kfc | kentucky fried wings | lost in the sauce",
  opps: 'opps!',
  noResFound: "No result found for your search! ",
  exploreKFCMenu: 'explore KFC Menu',
  cancel: 'cancel',
  yesConfirm: 'yes,Confirm',
  confirmAskingText: 'Are you sure you want to remove this product from your cart 🧐',
  edit: 'edit',
  items: 'Items',
  SubTotal: 'Sub Total',
  discount: 'Discount',
  vat: 'vat',
  deliveriCharge: 'Delivery Charge',
  grandTotal: 'Grand Total',
  offerApplied: 'Offer Applied 🤟🤟',
  gotIt: 'Got It',
  offerAvailText: 'Congratulations, complete your order o avail this offer',

  completeYourAddress: 'Complete your address',
  iWant: 'I Want',
  pickup: 'pickup',
  delivery: 'delivery',
  sorryNotDeliver: 'Soorry we do not deliver here',
  tagLocation: 'Tag location',
  address: 'Address',
  buildingName: 'Building Name',
  flatNo: 'Flat No',
  home: 'home',
  office: 'Office',
  hotel: 'Hotel',
  other: 'Other',
  confirmLocation: 'Confirm Location',

  checkOut: 'Checkout',
  wantOrder: 'I want my order:',
  deliverNow: 'Deliver Now',
  deliveryLater: 'Deliver Later',
  deliveryAddress: 'DELIVERY ADDRESS',
  contactLessDelivery: '100% contactless delivery',
  amountToBepaid: 'Amount to be paid',
  paymentMode: 'SELECT PAYMENT MODE',
  paymentMethods: 'Payment Method',
  makePayment: 'Make Payment',
  cashOnDelivery: 'Cash On Delivery',
  creditDebitcards: 'Credit/Debit Cards',
  visaCheckOut: 'Visa Check Out',


} as const

const ar = {
  // screens
  HomeScreen: 'HomeScreen',
  ChangeLocationBottomSheetScreen: 'ChangeLocationBottomSheetScreen',
  MapsScreen: 'MapsScreen',
  PopUpScreens: 'PopUpScreens',
  LoginScreen: 'LoginScreen',
  LoginScreen2: 'LoginScreen2',
  LoginPageCountryBottomSheetScreen: 'LoginPageCountryBottomSheetScreen',
  OTPScreen: 'OTPScreen',
  CreateProfileScreen: 'CreateProfileScreen',
  FontsScreen: 'FontsScreen',
  SplashScreen: 'SplashScreen',
  ExploreMenuScreen: 'ExploreMenuScreen',
  MenuCategorizeScreen: 'MenuCategorizeScreen',
  CartScreen: 'CartScreen',
  RemoveCartItemBottomSheetScreen: 'RemoveCartItemBottomSheetScreen',
  SearchScreen: 'SearchScreen',
  CheckOutScreen: 'CheckOutScreen',
  OrderHistoryScreens: 'OrderHistoryScreens',
  OfferAppliedScreen: "OfferAppliedScreen",
  HelpScreen: 'HelpScreen',
  Main: 'Main',
  Help: 'Help',


  // landing
  lickingGood: 'إنه لذيذ للغاية',

  // country bottomsheet
  welcome: 'مرحبًا بكم في كنتاكي',
  countryDescription: 'يمكنك الآن الطلب في البلدان التالية باستخدام هذا التطبيق. يرجى اختيار البلد الذي ترغب في تقديم الطلب فيه 😎',
  needToHaveLocalNumber: 'يجب أن يكون لديك رقم محلي',
  done: 'تم',



  // login
  KFC: 'كنتاكي',
  loginToUlock: 'سجّل الدخول لفتح',
  awesomeNewFeature: 'مميزات جديدة مذهلة',
  fingerLicking: 'طعم\nلا يُقاوم',
  dealAndOfferTxt: 'عروض\nوصفقات رائعة',
  easyOrdering: 'طلب\nسهل وسريع',
  chooseLanguage: 'اختر اللغة',
  english: 'English',
  arabic: 'العربية',
  uae: 'الإمارات',
  login: 'تسجيل الدخول',
  logout: 'Log Out',
  termsCondition: 'الشروط والأحكام',
  skipLogin: 'تخطي تسجيل الدخول',
  change: 'تغيير',

  // loginPage 2 
  welcome2: 'مرحبًا بكم في التطبيق الجديد',
  app: 'التطبيق',
  loginWIthNumberText: 'سجّل الدخول برقم صالح',
  mobileNumber: 'رقم الجوال',
  shouldBeXDigit: 'يجب أن يكون رقم الجوال مكونًا من 10 أرقام',
  EgMobile: 'eg 987 654 123',
  enterNumberPlaceHoler: 'Enter mobile no ',
  loginWithSocialHeader: 'سجّل الدخول عبر الحسابات الاجتماعية',
  facebook: 'فيسبوك',
  google: 'جوجل',
  tc: 'الشروط والأحكام',
  skipLoginAndContinue: 'تخطّ تسجيل الدخول واستمر',
  submit: 'إرسال',


  // otp auth
  otpText: 'رمز التحقق لمرة واحدة',
  enterOtpHeader: 'يرجى إدخال رمز التحقق المكون من 4 أرقام المرسل إلى',
  resendOtp: 'إعادة إرسال الرمز',
  callMe: 'اتصل بي',
  verifyText: 'تحقق',

  // create profile 
  createProfileHeader: 'إنشاء الملف الشخصي',
  enterYourDetails: 'يرجى إدخال بياناتك',
  name: 'الاسم',
  email: 'البريد الإلكتروني',
  save: 'حفظ',
  fieldIsMandatory: 'هذا الحقل إلزامي.',

  // home screen 
  deliveryTo: 'التوصيل إلى',
  exploreMore: 'استكشاف المزيد',
  viewAll: 'عرض الكل',
  deals: 'عروض',
  forOne: 'لشخص واحد',
  sideDeserts: 'حلويات جانبية',
  forSharing: 'للمشاركة',
  beverages: 'مشروبات',
  CurrentOrder: 'الطلب الحالي',
  trackOrder: 'تتبع الطلب',
  orderIdText: 'رقم الطلب',
  bestSeller: 'الأكثر مبيعًا',
  favourites: 'المفضلة',
  orderFromList: 'اطلب من قائمتك المفضلة من العناصر',
  orderNow: 'اطلب الآن',
  order: 'order',

  // location bottom sheet 
  consfirmLocation: 'تأكيد الموقع',
  consfirmLocationDescription: 'تم تحديد موقع التوصيل الخاص بك\nيرجى التأكيد للمتابعة ⛳',
  confirm: 'تأكيد',

  // sidebar 
  orderHistory: 'سجل الطلبات',
  dealsAndOffer: 'العروض والخصومات',
  greatMenu: 'قائمة رائعة',
  combo: 'وجبات كومبو',
  language: 'اللغة',
  languageToggle: 'language',
  country: 'البلد',
  callSupport: 'الاتصال بالدعم',
  faq: 'الأسئلة الشائعة',
  nutritionInfo: 'المعلومات الغذائية',
  pleaseSelectlanguage: 'يرجى اختيار اللغة',
  ChangeTheme: 'تغيير المظهر',

  // explore screen 
  exploreMenu: 'استكشف القائمة',
  AddToCart: 'أضف إلى السلة',
  customize: 'تخصيص',
  menuCategorizationHeader: 'تصنيفات القائمة',
  bestSeller2: 'الأكثر مبيعًا',
  viewCart: 'عرض السلة',
  youSaved: 'لقد وفّرت',
  cart: 'السلة',
  placeOrder: 'إتمام الطلب',
  addMoreItemsToCart: 'أضف المزيد من الأصناف إلى سلتك',
  applyCoupon: 'تطبيق الكوبون',
  WhatsNew: 'ما الجديد',
  bottomKFCDescription: "كنتاكي | أجنحة كنتاكي المقلية | غارق في الصوص",
  opps: 'عذرًا!',
  noResFound: 'لا توجد نتائج لبحثك!',
  exploreKFCMenu: 'استكشف قائمة KFC',
  cancel: 'إلغاء',
  yesConfirm: 'نعم، تأكيد',
  confirmAskingText: 'هل أنت متأكد أنك تريد إزالة هذا المنتج من سلتك؟ 🧐',
  edit: 'تعديل',
  items: 'عناصر',
  SubTotal: 'المجموع الفرعي',
  discount: 'Discount',
  vat: 'ضريبة القيمة المضافة',
  deliveriCharge: 'رسوم التوصيل',
  grandTotal: 'الإجمالي الكلي',
  offerApplied: 'تم تطبيق العرض 🤟🤟',
  gotIt: 'حسنًا',
  offerAvailText: 'تهانينا، أكمل طلبك للحصول على هذا العرض',

  completeYourAddress: 'أكمل عنوانك',
  iWant: 'أريد',
  pickup: 'استلام',
  delivery: 'توصيل',
  sorryNotDeliver: 'عذرًا، لا نوصل إلى هذا الموقع',
  tagLocation: 'تحديد الموقع',
  address: 'العنوان',
  buildingName: 'اسم المبنى',
  flatNo: 'رقم الشقة',
  home: 'منزل',
  office: 'مكتب',
  hotel: 'فندق',
  other: 'أخرى',
  confirmLocation: 'تأكيد الموقع',

  checkOut: 'الدفع',
  wantOrder: 'أريد طلبي:',
  deliverNow: 'التوصيل الآن',
  deliveryLater: 'التوصيل لاحقًا',
  deliveryAddress: 'عنوان التوصيل',
  contactLessDelivery: 'توصيل بدون تلامس 100%',
  amountToBepaid: 'المبلغ المستحق',
  paymentMode: 'اختر وسيلة الدفع',
  paymentMethods: 'payment Method',
  makePayment: 'إتمام الدفع',
  cashOnDelivery: 'الدفع عند الاستلام',
  creditDebitcards: 'بطاقات الائتمان/الخصم',
  visaCheckOut: 'الدفع عبر فيزا',

} as const

export const useStrings = () => {
  const { language } = useLanguage();
  return language === 'ar' ? ar : en;
};
